# Generated by Django 5.0.6 on 2024-06-30 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('empleados', '0002_remove_empleados_imagen_alter_empleados_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleados',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'OTRO')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
