# Generated by Django 5.0.6 on 2024-07-01 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('empleados', '0003_empleados_departamento_alter_empleados_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
    ]
