# Generated by Django 5.0.6 on 2024-07-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_habilidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
