# Generated by Django 5.0.6 on 2024-07-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_habilidades_options_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
    ]
