# Generated by Django 5.0.6 on 2024-07-01 03:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_empleado_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
